# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 00:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11)),
                ('items', models.CommaSeparatedIntegerField(max_length=10)),
                ('friends', models.ManyToManyField(related_name='_myuser_friends_+', to='savepablo.MyUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
