# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-22 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='points',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19),
        ),
    ]
