# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0002_myuser_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mWon',
            field=models.BooleanField(default=0),
        ),
    ]
