# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0004_myuser_mps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mps',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=100),
        ),
    ]
