# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0005_auto_20160326_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mps',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='points',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
        ),
    ]
