# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0006_auto_20160326_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='mps',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
        ),
    ]
