# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0007_auto_20160327_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='queued',
            field=models.BooleanField(default=0),
        ),
    ]
