# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0008_myuser_queued'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='opponent',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='savepablo.MyUser'),
        ),
    ]
