# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0009_myuser_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='opponent',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='savepablo.MyUser'),
        ),
    ]
