# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0010_auto_20160329_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ready',
            field=models.BooleanField(default=0),
        ),
    ]
