# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savepablo', '0011_myuser_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('p2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mps', models.DecimalField(decimal_places=1, default=0, max_digits=100)),
                ('count', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=1, default=0, max_digits=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='mMps',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='mPoints',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
        ),
    ]
