# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0013_auto_20160330_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='uuid',
            field=models.CharField(default=b'0', max_length=100),
        ),
    ]
