# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0015_auto_20160404_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='p1',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='savepablo.MyUser'),
        ),
        migrations.AlterField(
            model_name='game',
            name='p2',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='savepablo.MyUser'),
        ),
    ]
