# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0017_auto_20160417_1745'),
        ('savepablo', '0018_remove_myuser_blah'),
    ]

    operations = [
    ]
