# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0019_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='canClick',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='myuser',
            name='timeClick',
            field=models.IntegerField(default=0),
        ),
    ]
