# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0020_auto_20160419_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='second',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='third',
            field=models.BooleanField(default=0),
        ),
    ]
