# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepablo', '0021_auto_20160419_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='debuff',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
